// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjSoundBetterApi.Models;

public partial class TSkillCategory
{
    public int FSkillCategoryId { get; set; }

    public string FName { get; set; }

    public string FThumbnailPath { get; set; }

    public virtual ICollection<TSkill> TSkills { get; set; } = new List<TSkill>();
}